# Generated by Django 6.0.3 on 2026-03-20 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_logs_actor_i_ce2144_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_logs_action_474804_idx",
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["timestamp"], name="audit_logs_timesta_423be6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["actor_id", "action"], name="audit_logs_actor_i_cf1ffa_idx"
            ),
        ),
    ]
