# Generated by Django 6.0.3 on 2026-03-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="is_weekly_challenge",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quiz",
            name="weekly_bonus_xp",
            field=models.IntegerField(default=0),
        ),
    ]
