# Generated by Django 6.0.3 on 2026-03-20 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_quiz_is_weekly_challenge_quiz_weekly_bonus_xp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["is_published", "is_deleted", "topic"],
                name="quizzes_is_publ_b01881_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["is_weekly_challenge", "is_published"],
                name="quizzes_is_week_af07b4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="choice",
            constraint=models.CheckConstraint(
                condition=models.Q(("order__gte", 0)), name="choice_order_non_negative"
            ),
        ),
    ]
