# Generated by Django 6.0.3 on 2026-03-19 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attempts', '0001_initial'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon_key', models.CharField(max_length=50)),
                ('condition_type', models.CharField(choices=[('first_quiz', 'First Quiz Completed'), ('streak_5', '5 Day Streak'), ('perfect_hard', 'Perfect Score on Hard'), ('five_topics', '5 Different Topics'), ('comeback', 'Comeback After 3 Fails'), ('speed_demon', 'Finish in Half Time'), ('century', '100 Quizzes Completed')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'badges',
            },
        ),
        migrations.CreateModel(
            name='UserGameProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_total', models.IntegerField(default=0)),
                ('level', models.CharField(choices=[('novice', 'Novice'), ('apprentice', 'Apprentice'), ('scholar', 'Scholar'), ('expert', 'Expert'), ('master', 'Master')], default='novice', max_length=15)),
                ('streak_easy', models.IntegerField(default=0)),
                ('streak_medium', models.IntegerField(default=0)),
                ('streak_hard', models.IntegerField(default=0)),
                ('streak_freeze_count', models.IntegerField(default=1)),
                ('last_easy_attempt', models.DateField(blank=True, null=True)),
                ('last_medium_attempt', models.DateField(blank=True, null=True)),
                ('last_hard_attempt', models.DateField(blank=True, null=True)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_game_profiles',
            },
        ),
        migrations.CreateModel(
            name='PersonalBest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=10)),
                ('best_score', models.FloatField()),
                ('achieved_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_best_records', to='attempts.quizattempt')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_bests', to='quizzes.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_bests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_bests',
                'unique_together': {('user', 'topic', 'difficulty')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_badges',
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserTopicStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('avg_score', models.FloatField(default=0.0)),
                ('best_score', models.FloatField(default=0.0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='quizzes.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_topic_stats',
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
