# Generated by Django 6.0.3 on 2026-03-20 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0001_initial"),
        ("quizzes", "0003_quiz_quizzes_is_publ_b01881_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usertopicstat",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="usertopicstat",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("easy", "Easy"),
                    ("medium", "Medium"),
                    ("hard", "Hard"),
                    ("all", "All"),
                ],
                default="all",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usertopicstat",
            unique_together={("user", "topic", "difficulty")},
        ),
        migrations.AddIndex(
            model_name="usertopicstat",
            index=models.Index(
                fields=["user", "last_attempted_at"],
                name="user_topic__user_id_7c5a71_idx",
            ),
        ),
    ]
